<?php

namespace App\Exports;

use App\Models\ZReading;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class ZReadingExport implements FromCollection, WithHeadings, WithTitle, WithStyles, ShouldAutoSize
{
    public function __construct(private readonly ZReading $reading)
    {
    }

    public function collection(): Collection
    {
        $summary = $this->reading->snapshot;

        $rows = collect([
            ['Z Reading Number', $this->reading->reading_number],
            ['Business Date', optional($this->reading->business_date)->format('Y-m-d')],
            ['Terminal', $this->reading->terminal?->name ?? ''],
            ['Branch', $this->reading->branch?->name ?? ''],
            ['Generated By', $this->reading->generatedBy?->name ?? ''],
            ['Generated At', optional($this->reading->generated_at)->format('Y-m-d H:i:s')],
            ['Status', strtoupper($this->reading->status)],
            ['', ''],
            ['Gross Sales', number_format($summary['gross_sales'] ?? 0, 2)],
            ['PWD/Senior Discounts', number_format($summary['total_discount'] ?? 0, 2)],
            ['  Senior Citizen Discount', number_format($summary['senior_discount_amount'] ?? 0, 2) . ' (' . ($summary['senior_count'] ?? 0) . ' tx)'],
            ['  PWD Discount', number_format($summary['pwd_discount_amount'] ?? 0, 2) . ' (' . ($summary['pwd_count'] ?? 0) . ' tx)'],
            ['  Other Discounts', number_format($summary['other_discount_amount'] ?? 0, 2)],
            ['Total Promotional Discounts', number_format($summary['promo_discount_amount'] ?? 0, 2)],
            ['  Coupon Discounts', number_format($summary['promo_coupon_discount_amount'] ?? 0, 2)],
            ['  Manual Promotional Discounts', number_format($summary['promo_manual_discount_amount'] ?? 0, 2)],
            ['  Discounted Transactions', $summary['promo_discount_count'] ?? 0],
            ['Net Sales After Promo Discounts', number_format($summary['net_sales_after_promo_discount'] ?? 0, 2)],
            ['VATable Sales', number_format($summary['vatable_sales'] ?? 0, 2)],
            ['VAT-Exempt Sales', number_format($summary['vat_exempt_sales'] ?? 0, 2)],
            ['Zero-Rated Sales', number_format($summary['zero_rated_sales'] ?? 0, 2)],
            ['VAT Amount', number_format($summary['vat_amount'] ?? 0, 2)],
            ['Net Sales', number_format($summary['net_sales'] ?? 0, 2)],
            ['Number of Transactions', $summary['transaction_count'] ?? 0],
            ['Customers Served', $summary['customers_served'] ?? 0],
            ['Refunds / Void Transactions', ($summary['voided_count'] ?? 0) . ' (' . number_format($summary['voided_amount'] ?? 0, 2) . ')'],
            ['', ''],
            ['Payment Method Breakdown', ''],
        ]);

        foreach (($summary['by_method'] ?? []) as $row) {
            $rows->push(['  ' . ucfirst($row['method'] ?? ''), number_format($row['amount'] ?? 0, 2) . ' (' . ($row['transactions'] ?? 0) . ' tx)']);
        }

        return $rows;
    }

    public function headings(): array
    {
        return ['Field', 'Value'];
    }

    public function title(): string
    {
        return 'Z Reading';
    }

    public function styles(Worksheet $sheet): array
    {
        return [
            1 => [
                'font' => ['bold' => true, 'color' => ['argb' => 'FFFFFFFF']],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['argb' => 'FF2D3748'],
                ],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
        ];
    }
}
