@extends('layouts.app')
@section('page_title', $reading->reading_number . ' - Dianne\'s Seafood House')
@section('content')
<x-page-header :title="$reading->reading_number" subtitle="Z Reading — End-of-Day Closing Report" icon="lock">
    <div class="d-flex gap-2 d-print-none">
        <a href="{{ route('reports.z-reading.export-excel', $reading) }}" class="btn btn-light text-primary">
            <i data-lucide="file-spreadsheet" class="me-1"></i> Export Excel
        </a>
        <a href="{{ route('reports.z-reading.export-pdf', $reading) }}" class="btn btn-light text-primary">
            <i data-lucide="file-text" class="me-1"></i> Export PDF
        </a>
        <button type="button" class="btn btn-light text-primary" onclick="window.print()">
            <i data-lucide="printer" class="me-1"></i> Print
        </button>
        <a href="{{ route('reports.z-reading.index') }}" class="btn btn-light text-primary">
            <i data-lucide="arrow-left" class="me-1"></i> Back
        </a>
    </div>
</x-page-header>

<div class="container-xl px-4">
    @include('layouts.alerts')

    @if($reading->status === 'voided')
    <div class="alert alert-danger">
        <i data-lucide="alert-triangle" class="me-1"></i>
        This Z Reading was <strong>voided</strong> by {{ $reading->voidedBy->name ?? '—' }} on {{ $reading->voided_at?->format('M d, Y h:i A') }}.
        Reason: {{ $reading->void_reason }}
    </div>
    @else
    <div class="alert alert-success">
        <i data-lucide="lock" class="me-1"></i>
        This Z Reading is <strong>locked</strong> and reflects the final, permanent totals for this terminal's business day.
    </div>
    @endif

    <div class="card shadow-sm mb-3">
        <div class="card-body">
            <dl class="row mb-0 small">
                <dt class="col-sm-2">Z Number</dt><dd class="col-sm-4 fw-bold">{{ $reading->reading_number }}</dd>
                <dt class="col-sm-2">Business Date</dt><dd class="col-sm-4">{{ $reading->business_date->format('M d, Y') }}</dd>
                <dt class="col-sm-2">Terminal</dt><dd class="col-sm-4">{{ $reading->terminal->name ?? '—' }} ({{ $reading->terminal->code ?? '—' }})</dd>
                <dt class="col-sm-2">Branch</dt><dd class="col-sm-4">{{ $reading->branch->name ?? '—' }}</dd>
                <dt class="col-sm-2">Generated By</dt><dd class="col-sm-4">{{ $reading->generatedBy->name ?? '—' }}</dd>
                <dt class="col-sm-2">Date/Time Closed</dt><dd class="col-sm-4">{{ $reading->generated_at->format('M d, Y h:i A') }}</dd>
            </dl>
        </div>
    </div>

    @include('reports.partials.reading-summary', ['summary' => $summary])

    @if($reading->status === 'locked' && auth()->user()->isAdmin())
    <div class="card shadow-sm d-print-none">
        <div class="card-header fw-semibold text-danger"><i data-lucide="alert-triangle" class="me-1"></i> Administrator: Void This Z Reading</div>
        <div class="card-body">
            <p class="text-muted small">Voiding does not delete this report — it stays on record for audit purposes, but unlocks the terminal so a corrected Z Reading can be generated for this date.</p>
            <form method="POST" action="{{ route('reports.z-reading.void', $reading) }}" onsubmit="return confirm('Void this Z Reading? This action is recorded for audit purposes.')" class="row g-2">
                @csrf
                <div class="col-md-8">
                    <input type="text" name="void_reason" class="form-control" placeholder="Reason for voiding (required)" required>
                </div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-outline-danger w-100">Void Z Reading</button>
                </div>
            </form>
        </div>
    </div>
    @endif
</div>
@endsection

@push('styles')
<style>
@media print {
    .sidebar, header.glass-header, .d-print-none { display: none !important; }
    .main-content { margin: 0 !important; }
    .container-xl { max-width: 100% !important; }
    .card { break-inside: avoid; }
}
</style>
@endpush
