@extends('layouts.app')
@section('page_title', 'Z Reading - Dianne\'s Seafood House')
@section('content')
<x-page-header title="Z Reading" subtitle="End-of-day closing reports — locks and sequences each terminal's business day" icon="lock">
</x-page-header>

<div class="container-xl px-4">
    @include('layouts.alerts')

    <div class="card shadow-sm mb-4">
        <div class="card-header fw-semibold"><i data-lucide="plus-circle" class="me-1"></i> Generate Z Reading</div>
        <div class="card-body">
            @if($terminals->isEmpty())
            <div class="alert alert-warning mb-0">
                No active POS terminals found. <a href="{{ route('pos-terminals.index') }}">Add a terminal</a> first.
            </div>
            @else
            <form method="GET" action="{{ route('reports.z-reading.preview') }}" class="row g-2 align-items-end">
                <div class="col-md-4">
                    <label class="form-label fw-semibold">Terminal <span class="text-danger">*</span></label>
                    <select name="pos_terminal_id" class="form-select" required>
                        <option value="">Select Terminal</option>
                        @foreach($terminals as $terminal)
                        <option value="{{ $terminal->id }}">{{ $terminal->name }} ({{ $terminal->code }}) — {{ $terminal->branch->name ?? '' }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-md-3">
                    <label class="form-label fw-semibold">Business Date <span class="text-danger">*</span></label>
                    <input type="date" name="business_date" class="form-control" value="{{ $today }}" max="{{ $today }}" required>
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-primary">
                        <i data-lucide="eye" class="me-1"></i> Preview
                    </button>
                </div>
            </form>
            @endif
        </div>
    </div>

    <div class="card shadow-sm mb-4">
        <div class="card-body">
            <form method="GET" action="{{ route('reports.z-reading.index') }}" class="row g-2 align-items-end">
                <div class="col-auto d-flex gap-2">
                    <button type="submit" class="btn btn-secondary btn-sm">Refresh</button>
                </div>
            </form>
        </div>
    </div>

    <div class="card shadow-sm">
        <div class="card-header fw-semibold"><i data-lucide="list" class="me-1"></i> Generated Z Readings</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped" id="zReadingsTable">
                    <thead class="table-dark">
                        <tr>
                            <th>Z Number</th><th>Business Date</th><th>Terminal</th><th>Branch</th>
                            <th>Generated By</th><th>Generated At</th><th>Status</th><th></th>
                        </tr>
                    </thead>
                    <tbody id="tableBody"><tr><td colspan="8" class="text-center py-4"><div class="spinner-border text-primary" role="status"><span class="visually-hidden">Loading...</span></div></td></tr></tbody>
                </table>
            </div>
        </div>
        <div class="card-footer d-flex justify-content-between align-items-center flex-wrap gap-2">
            <div id="tableInfo" class="text-muted small"></div>
            <nav aria-label="Z Readings pagination">
                <ul id="pagination" class="pagination pagination-sm mb-0"></ul>
            </nav>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script src="{{ asset('js/index-table-bridge.js') }}"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    IndexTableBridge.init({
        tableId: 'zReadingsTable',
        dataUrl: @json(route('reports.z-reading.data')),
        emptyMessage: 'No Z Readings generated yet.',
        colspan: 8,
        renderRow: function (row, ctx) {
            const statusBadge = row.status === 'locked' ? 'bg-success' : 'bg-secondary';
            return `
                <tr>
                    <td class="fw-semibold small">${ctx.escapeHtml(row.reading_number)}</td>
                    <td class="small">${ctx.escapeHtml(row.business_date)}</td>
                    <td>${ctx.escapeHtml(row.terminal_name || '—')}</td>
                    <td class="text-muted small">${ctx.escapeHtml(row.branch_name || '—')}</td>
                    <td class="text-muted small">${ctx.escapeHtml(row.generated_by || '—')}</td>
                    <td class="text-nowrap small">${ctx.escapeHtml(row.generated_at)}</td>
                    <td><span class="badge ${statusBadge}">${ctx.escapeHtml(row.status.charAt(0).toUpperCase() + row.status.slice(1))}</span></td>
                    <td class="table-actions-cell"><a href="${row.show_url}" class="btn btn-sm btn-info text-white" title="View"><i data-lucide="eye"></i></a></td>
                </tr>
            `;
        }
    });
});
</script>
@endpush
